# Generated by Django 3.0.7 on 2020-07-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200701_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('kind', models.IntegerField(choices=[(1, 'horror'), (2, 'comedy'), (3, 'drama'), (0, 'unknown')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ExtraInfo'),
        ),
    ]
