# Generated by Django 3.0.7 on 2020-07-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200701_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='kind',
            field=models.IntegerField(choices=[(3, 'drama'), (1, 'horror'), (0, 'unknown'), (2, 'comedy')], default=0),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(default='')),
                ('stars', models.IntegerField(default=3)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
    ]
