# Generated by Django 3.0.7 on 2020-07-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200701_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='kind',
            field=models.IntegerField(choices=[(1, 'horror'), (0, 'unknown'), (3, 'drama'), (2, 'comedy')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.Movie'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('movie', models.ManyToManyField(to='api.Movie')),
            ],
        ),
    ]
